import './js/header.js';
import './js/hero.js';
import './js/about';
import './js/benefits';
import './js/projects';
import './js/faq';
import './js/covers';
import './js/reviews';
import './js/work';
